import {createDinoScene} from './dino-scene.js';
import {firebaseReady,onAuth,login,logout,resetPassword,getProfile,listCoupons,createCoupon,setCouponProgress,listMural,uploadMural,listMessages,sendMessage,markMessageRead,listUsers,requestPushPermission,onForegroundMessage} from './firebase-service.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let currentUser=null,profile=null,coupons=[],mural=[],messages=[],users=[],filter='active',localDemoMedia=[];
const screens=['#introScreen','#letterScreen','#authScreen','#appScreen'];
function showScreen(id){screens.forEach(x=>$(x).classList.toggle('is-visible',x===id));}
function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),2600)}
function fmtDate(d){return new Intl.DateTimeFormat('es-CO',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(d));}
function timeAgo(d){const sec=Math.floor((Date.now()-new Date(d).getTime())/1000);if(sec<60)return'ahora';if(sec<3600)return`hace ${Math.floor(sec/60)} min`;if(sec<86400)return`hace ${Math.floor(sec/3600)} h`;return fmtDate(d)}
function escapeHtml(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}

const cleanupDino=createDinoScene($('#dinoStage'),()=>{$('#letterDelivery').hidden=false;});
$('#skipIntroBtn').onclick=()=>{$('#letterDelivery').hidden=false;};
$('#openLetterBtn').onclick=()=>showScreen('#letterScreen');
$('#continueToLoginBtn').onclick=()=>showScreen('#authScreen');
$('#togglePasswordBtn').onclick=()=>{const x=$('#loginPassword');x.type=x.type==='password'?'text':'password';};
$('#forgotPasswordBtn').onclick=async()=>{const email=$('#loginEmail').value.trim();if(!email)return toast('Escribe primero tu correo.');try{await resetPassword(email);toast('Se envió el enlace de restablecimiento.');}catch(e){toast('No fue posible enviar el enlace.');console.error(e)}};
$('#loginForm').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;try{await login($('#loginEmail').value.trim(),$('#loginPassword').value);if(!firebaseReady){await enterApp({uid:'demo-user',email:$('#loginEmail').value.trim()||'demo@dinocupones.app'});toast('Modo demo: conecta Firebase para usar datos reales.')}}catch(err){toast(humanAuthError(err));console.error(err)}finally{btn.disabled=false}};
$('#logoutBtn').onclick=async()=>{await logout();currentUser=null;profile=null;showScreen('#authScreen');};
function humanAuthError(err){const c=err?.code||'';if(c.includes('invalid-credential'))return'Usuario o contraseña incorrectos.';if(c.includes('too-many-requests'))return'Demasiados intentos. Intenta más tarde.';return'No se pudo iniciar sesión.'}

onAuth(async user=>{if(firebaseReady&&user)await enterApp(user);else if(firebaseReady&&!user&&$('#introScreen').classList.contains('is-visible')===false)showScreen('#authScreen');});
async function enterApp(user){currentUser=user;profile=await getProfile(user.uid);$('#userName').textContent=profile.displayName||'Dino';$('#userRole').textContent=profile.role==='admin'?'Administrador':'Invitado especial';$('#userAvatar').textContent=(profile.displayName||'D')[0].toUpperCase();$('#adminTabBtn').hidden=profile.role!=='admin';showScreen('#appScreen');await refreshAll();if('serviceWorker'in navigator){try{await navigator.serviceWorker.register('./firebase-messaging-sw.js');if(firebaseReady) setTimeout(()=>requestPushPermission(user.uid).catch(()=>{}),1400);}catch(e){console.warn(e)}}}
async function refreshAll(){[coupons,mural,messages]=await Promise.all([listCoupons(currentUser.uid),listMural(),listMessages(currentUser.uid)]);localDemoMedia.length&&mural.unshift(...localDemoMedia);renderCoupons();renderMural();renderMessages();renderHero();if(profile.role==='admin'){users=await listUsers();renderAdminUsers();renderRecipients();renderAdminMedia();}}
function renderHero(){const active=coupons.filter(c=>c.status==='active').sort((a,b)=>new Date(a.expiresAt)-new Date(b.expiresAt));$('#nextCouponTitle').textContent=active[0]?.title||'Crear un nuevo recuerdo';}

$$('.tab-btn').forEach(b=>b.onclick=()=>{const tab=b.dataset.tab;$$('.tab-btn').forEach(x=>x.classList.toggle('is-active',x===b));$$('.tab-panel').forEach(x=>x.classList.remove('is-active'));`#${tab}Tab`&&$(`#${tab}Tab`).classList.add('is-active');});
$$('.chip').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;$$('.chip').forEach(x=>x.classList.toggle('is-active',x===b));renderCoupons();});
function renderCoupons(){const data=coupons.filter(c=>c.status===filter);$('#couponGrid').innerHTML=data.length?data.map(c=>`<article class="coupon-card" data-id="${c.id}"><div class="coupon-icon">${c.emoji||'💜'}</div><span class="status-pill ${c.status}">${labelStatus(c.status)}</span><h4>${escapeHtml(c.title)}</h4><p>${escapeHtml(c.activity||'')}</p><div class="coupon-footer"><span class="coupon-date">Vence ${fmtDate(c.expiresAt)}</span><button class="mini-btn" data-open-coupon="${c.id}">Ver cupón</button></div></article>`).join(''):`<div class="empty-state"><strong>No hay cupones aquí.</strong>Cuando aparezca uno, este espacio dejará de estar tan tranquilo. 🦕</div>`;$$('[data-open-coupon]').forEach(b=>b.onclick=()=>openCoupon(b.dataset.openCoupon));}
function labelStatus(s){return({active:'Activo',pending:'Por completar',completed:'Canjeado',expired:'Vencido'})[s]||s;}
function openCoupon(id){const c=coupons.find(x=>x.id===id);if(!c)return;$('#couponDialogEmoji').textContent=c.emoji||'💜';const st=$('#couponDialogStatus');st.className=`status-pill ${c.status}`;st.textContent=labelStatus(c.status);$('#couponDialogTitle').textContent=c.title;$('#couponDialogActivity').textContent=c.activity;$('#couponDialogExpiry').textContent=fmtDate(c.expiresAt);const a=$('#couponDialogActions');a.innerHTML='';if(c.status==='active')a.innerHTML=`<button class="primary-btn" type="button" data-status="pending">Empezar aventura</button>`;if(c.status==='pending')a.innerHTML=`<button class="primary-btn" type="button" data-status="completed">Marcar como canjeado</button>`;a.querySelector('[data-status]')?.addEventListener('click',async e=>{await setCouponProgress(currentUser.uid,c.id,e.target.dataset.status);$('#couponDialog').close();coupons=await listCoupons(currentUser.uid);renderCoupons();renderHero();toast('Cupón actualizado 💜')});$('#couponDialog').showModal();}

$('#openUploadBtn').onclick=()=>{renderUploadCoupons();$('#uploadDialog').showModal();};$('#closeUploadBtn').onclick=()=>$('#uploadDialog').close();
$('#uploadFile').onchange=()=>{const f=$('#uploadFile').files[0],p=$('#uploadPreview');if(!f){p.textContent='El archivo aparecerá aquí.';return}const u=URL.createObjectURL(f);p.innerHTML=f.type.startsWith('video/')?`<video src="${u}" controls></video>`:`<img src="${u}" alt="Vista previa">`;};
function renderUploadCoupons(){$('#uploadCoupon').innerHTML='<option value="">Sin cupón específico</option>'+coupons.filter(c=>c.status!=='expired').map(c=>`<option value="${c.id}">${escapeHtml(c.title)}</option>`).join('');}
$('#uploadForm').onsubmit=async e=>{e.preventDefault();const file=$('#uploadFile').files[0];if(!file)return;const btn=$('#uploadSubmitBtn');btn.disabled=true;btn.textContent='Subiendo...';try{const item=await uploadMural({uid:currentUser.uid,couponId:$('#uploadCoupon').value,caption:$('#uploadCaption').value.trim(),file});if(!firebaseReady)localDemoMedia.unshift(item);mural=await listMural();if(!firebaseReady)mural.unshift(...localDemoMedia);renderMural();if(profile.role==='admin')renderAdminMedia();$('#uploadForm').reset();$('#uploadPreview').textContent='El archivo aparecerá aquí.';$('#uploadDialog').close();toast('Recuerdo guardado en el DinoMural.');}catch(err){console.error(err);toast('No se pudo subir el recuerdo.');}finally{btn.disabled=false;btn.textContent='Guardar recuerdo'}};
function renderMural(){const g=$('#muralGrid');g.innerHTML=mural.length?mural.map(m=>`<article class="mural-card">${m.type==='video'?`<video class="mural-media" src="${m.mediaUrl||m.localUrl}" controls preload="metadata"></video>`:`<img class="mural-media" src="${m.mediaUrl||m.localUrl}" alt="Recuerdo del DinoMural" loading="lazy">`}<div class="mural-copy"><p>${escapeHtml(m.caption||'Un recuerdo sin título, pero con historia.')}</p><small>${timeAgo(m.createdAt||new Date())}${m.fileName?` · ${escapeHtml(m.fileName)}`:''}</small></div></article>`).join(''):`<div class="empty-state"><strong>El mural todavía está vacío.</strong>La primera foto siempre es la que empieza la historia.</div>`;}

$('#notificationBtn').onclick=()=>toggleDrawer(true);$('#closeNotificationsBtn').onclick=()=>toggleDrawer(false);$('#drawerBackdrop').onclick=()=>toggleDrawer(false);function toggleDrawer(open){$('#notificationDrawer').classList.toggle('is-open',open);$('#drawerBackdrop').classList.toggle('is-open',open);$('#notificationDrawer').setAttribute('aria-hidden',String(!open));}
function renderMessages(){const unread=messages.filter(m=>!m.read).length;$('#notificationBadge').hidden=!unread;$('#notificationBadge').textContent=unread;$('#notificationList').innerHTML=messages.length?messages.map(m=>`<button class="notification-item ${m.read?'':'unread'}" data-message-id="${m.id}" type="button"><strong>${escapeHtml(m.title)}</strong><p>${escapeHtml(m.body)}</p><small>${timeAgo(m.createdAt||new Date())}</small></button>`).join(''):`<div class="empty-state"><strong>Sin mensajes.</strong>Cuando llegue uno aparecerá aquí.</div>`;$$('[data-message-id]').forEach(b=>b.onclick=async()=>{await markMessageRead(b.dataset.messageId);const m=messages.find(x=>x.id===b.dataset.messageId);if(m)m.read=true;renderMessages();});}
onForegroundMessage(payload=>{const n=payload.notification||{};toast(n.title?`${n.title}: ${n.body||''}`:'Llegó una nueva notificación.');refreshAll();});

$('#couponForm').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;try{await createCoupon({title:$('#couponTitle').value.trim(),activity:$('#couponActivity').value.trim(),expiresAt:new Date($('#couponExpiry').value),createdBy:currentUser.uid});e.target.reset();coupons=await listCoupons(currentUser.uid);renderCoupons();renderHero();toast('Cupón publicado.');}catch(err){console.error(err);toast('No se pudo publicar el cupón.');}finally{btn.disabled=false}};
$('#messageForm').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;try{await sendMessage({targetUid:$('#messageRecipient').value,title:$('#messageTitle').value.trim(),body:$('#messageBody').value.trim(),createdBy:currentUser.uid});e.target.reset();messages=await listMessages(currentUser.uid);renderMessages();toast('Mensaje enviado.');}catch(err){console.error(err);toast('No se pudo enviar el mensaje.');}finally{btn.disabled=false}};
function renderRecipients(){$('#messageRecipient').innerHTML='<option value="all">Todos</option>'+users.filter(u=>u.role!=='admin'||u.uid!==currentUser.uid).map(u=>`<option value="${u.uid}">${escapeHtml(u.displayName||u.email||u.uid)}</option>`).join('');}
function renderAdminUsers(){$('#adminUsersList').innerHTML=users.map(u=>`<div class="admin-row"><div><strong>${escapeHtml(u.displayName||'Sin nombre')}</strong><small>${escapeHtml(u.email||u.uid)} · ${u.role||'user'}</small></div><button class="mini-btn" data-reset-email="${escapeHtml(u.email||'')}" type="button">Restablecer</button></div>`).join('');$$('[data-reset-email]').forEach(b=>b.onclick=async()=>{if(!b.dataset.resetEmail)return toast('Este usuario no tiene correo registrado.');try{await resetPassword(b.dataset.resetEmail);toast('Enlace de restablecimiento enviado.');}catch(e){toast('No se pudo enviar el enlace.');}})}
function renderAdminMedia(){$('#adminMediaList').innerHTML=mural.length?mural.map(m=>`<div class="admin-row"><div><strong>${escapeHtml(m.fileName||'Recuerdo')}</strong><small>${m.type||'archivo'} · ${timeAgo(m.createdAt||new Date())}</small></div>${m.mediaUrl?`<a class="mini-btn" href="${m.mediaUrl}" target="_blank" rel="noopener">Descargar</a>`:'<span class="mini-btn">Demo</span>'}</div>`).join(''):'<div class="empty-state"><strong>Sin archivos.</strong></div>';}

if(!firebaseReady) console.info('DinoCupones está ejecutándose en modo demo. Configura js/firebase-config.js para conectar Firebase.');
window.addEventListener('beforeunload',()=>cleanupDino?.());
